sudo: required
services:
  - docker

before_install:
  - docker build -t samratluintel/docker-react -f Dockerfile.dev .

script:
  - docker run samratluintel/docker-react CI=true npm run test -- --coverage
