sudo: required
services:
  - docker

before_install:
  - docker build -t samratluintel/docker-react -f Dockerfile.dev .

# script:
#   - docker run samratluintel/docker-react npm run coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-038284067175"
  bucket_path: "docker-react"
  branches:
    only:
      - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
